export const CHANGE_COLOR_ON_DRAWING_BOARD = "CHANGE_COLOR_ON_DRAWING";
export const PAINT_ON_DRAWING_BOARD = "PAINT_ON_DRAWING_BOARD";
export const ADD_NEW_PATH_ON_RAWING_BOARD = "ADD_NEW_PATH_ON_RAWING_BOARD";
